/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_ljbo82_jserial_NativeSerialPort */

#ifndef _Included_com_github_ljbo82_jserial_NativeSerialPort
#define _Included_com_github_ljbo82_jserial_NativeSerialPort
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_ljbo82_jserial_NativeSerialPort_IO
#define com_github_ljbo82_jserial_NativeSerialPort_IO -3L
#undef com_github_ljbo82_jserial_NativeSerialPort_ACCESS
#define com_github_ljbo82_jserial_NativeSerialPort_ACCESS -4L
#undef com_github_ljbo82_jserial_NativeSerialPort_TIMEOUT
#define com_github_ljbo82_jserial_NativeSerialPort_TIMEOUT -7L
/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    getNativeLibVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_getNativeLibVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    getPortNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_getPortNames
  (JNIEnv *, jclass);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    getCurrentError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_getCurrentError
  (JNIEnv *, jclass);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    clearCurrentError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_clearCurrentError
  (JNIEnv *, jclass);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    close
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    config
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_config
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    purge
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_purge
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    getBaud
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_getBaud
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    getDataBits
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_getDataBits
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    getParity
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_getParity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    getStopBits
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_getStopBits
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    setReadTimeout
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_setReadTimeout
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    getReadTimeout
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_getReadTimeout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    read
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_read
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    write
 * Signature: (J[BII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_write
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    flush
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_flush
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
