/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_ljbo82_jserial_NativeSerialPort */

#ifndef _Included_com_github_ljbo82_jserial_NativeSerialPort
#define _Included_com_github_ljbo82_jserial_NativeSerialPort
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_ljbo82_jserial_NativeSerialPort_IO
#define com_github_ljbo82_jserial_NativeSerialPort_IO -3L
#undef com_github_ljbo82_jserial_NativeSerialPort_ACCESS
#define com_github_ljbo82_jserial_NativeSerialPort_ACCESS -4L
#undef com_github_ljbo82_jserial_NativeSerialPort_TIMEOUT
#define com_github_ljbo82_jserial_NativeSerialPort_TIMEOUT -7L
/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    get_native_lib_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_get_1native_1lib_1version
  (JNIEnv *, jclass);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    get_port_names
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_get_1port_1names
  (JNIEnv *, jclass);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    get_current_error
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_get_1current_1error
  (JNIEnv *, jclass);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    clear_current_error
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_clear_1current_1error
  (JNIEnv *, jclass);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    close
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    config
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_config
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    purge
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_purge
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    get_baud
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_get_1baud
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    get_data_bits
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_get_1data_1bits
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    get_parity
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_get_1parity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    get_stop_bits
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_get_1stop_1bits
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    set_read_timeout
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_set_1read_1timeout
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    get_read_timeout
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_get_1read_1timeout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    read
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_read
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    write
 * Signature: (J[BII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_write
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_github_ljbo82_jserial_NativeSerialPort
 * Method:    flush
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_ljbo82_jserial_NativeSerialPort_flush
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
